"""initial_schema

Revision ID: e667026e8a4f
Revises: 
Create Date: 2026-07-26 17:53:56.959754

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = 'e667026e8a4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_fingerprints',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('time_window', sa.String(length=64), nullable=True),
    sa.Column('primary_event_id', sa.String(length=36), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_fingerprints_fingerprint'), 'event_fingerprints', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_event_fingerprints_primary_event_id'), 'event_fingerprints', ['primary_event_id'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('success_probability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('information_sources',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credibility', sa.String(length=32), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_upload_id', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_sources_user_upload_id'), 'information_sources', ['user_upload_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('half_life_days', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_region'), 'risk_factors', ['region'], unique=False)
    op.create_table('risk_propagation_logs',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=True),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_risk', sa.Float(), nullable=False),
    sa.Column('final_risk', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_propagation_logs_event_id'), 'risk_propagation_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_risk_propagation_logs_goal_id'), 'risk_propagation_logs', ['goal_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_goal_id', sa.String(length=36), nullable=True),
    sa.Column('preferred_pathway_id', sa.String(length=36), nullable=True),
    sa.Column('priority_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=16), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('implicit_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notify_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_user_profiles_external_id'), 'user_profiles', ['external_id'], unique=False)
    op.create_table('assertions',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('conflicting_with_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertions_scenario_id'), 'assertions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_assertions_source_id'), 'assertions', ['source_id'], unique=False)
    op.create_table('events',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_flag_level', sa.String(length=16), nullable=True),
    sa.Column('risk_flag_type', sa.String(length=32), nullable=True),
    sa.Column('risk_flag_urgency', sa.String(length=16), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('half_life_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=False)
    op.create_index('ix_events_subject_action', 'events', ['subject', 'action'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_source_id'), 'metric_snapshots', ['source_id'], unique=False)
    op.create_index('ix_metrics_name_region', 'metric_snapshots', ['name', 'region'], unique=False)
    op.create_table('notification_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('risk_factor_id', sa.String(length=36), nullable=True),
    sa.Column('impact_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_event_id'), 'notification_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_risk_factor_id'), 'notification_logs', ['risk_factor_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notification_logs', ['user_id', 'status'], unique=False)
    op.create_table('pathways',
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_pathway_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_pathway_id'], ['pathways.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pathways_goal', 'pathways', ['goal_id'], unique=False)
    op.create_index(op.f('ix_pathways_goal_id'), 'pathways', ['goal_id'], unique=False)
    op.create_index(op.f('ix_pathways_scenario_id'), 'pathways', ['scenario_id'], unique=False)
    op.create_table('relationships',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationships_object', 'relationships', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_relationships_object_id'), 'relationships', ['object_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index('ix_relationships_subject', 'relationships', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_relationships_subject_id'), 'relationships', ['subject_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('overall_risk', sa.Float(), nullable=False),
    sa.Column('factor_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_goal_id'), 'risk_assessments', ['goal_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_scenario_id'), 'risk_assessments', ['scenario_id'], unique=False)
    op.create_index('ix_risk_assessments_user_goal', 'risk_assessments', ['user_id', 'goal_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_user_id'), 'risk_assessments', ['user_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_scenario_id', sa.String(length=36), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success_probability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('key_risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_threshold', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_goal_id'), 'scenarios', ['goal_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_category'), 'user_memories', ['category'], unique=False)
    op.create_index('ix_user_memories_importance', 'user_memories', [sa.literal_column('importance DESC')], unique=False)
    op.create_index('ix_user_memories_user_category', 'user_memories', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_table('user_uploads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('user_credibility', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('legal_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_uploads_user', 'user_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_uploads_user_id'), 'user_uploads', ['user_id'], unique=False)
    op.create_table('requirements',
    sa.Column('pathway_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gap_status', sa.String(length=16), nullable=False),
    sa.Column('gap_delta', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_pathway', 'requirements', ['pathway_id'], unique=False)
    op.create_index(op.f('ix_requirements_pathway_id'), 'requirements', ['pathway_id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_runs_scenario', 'scenario_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)

    # Deferred FK constraints for the goals ↔ user_profiles circular dependency.
    # Both columns reference each other, so the constraints must be added after
    # both tables exist.
    op.create_foreign_key(
        'fk_goals_user_id_user_profiles',
        'goals',
        'user_profiles',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_user_profiles_primary_goal_id_goals',
        'user_profiles',
        'goals',
        ['primary_goal_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop deferred FK constraints first (circular dependency).
    op.drop_constraint('fk_user_profiles_primary_goal_id_goals', 'user_profiles', type_='foreignkey')
    op.drop_constraint('fk_goals_user_id_user_profiles', 'goals', type_='foreignkey')
    op.drop_index(op.f('ix_scenario_runs_scenario_id'), table_name='scenario_runs')
    op.drop_index('ix_scenario_runs_scenario', table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_requirements_pathway_id'), table_name='requirements')
    op.drop_index('ix_requirements_pathway', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_user_uploads_user_id'), table_name='user_uploads')
    op.drop_index('ix_user_uploads_user', table_name='user_uploads')
    op.drop_table('user_uploads')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index('ix_user_memories_user_category', table_name='user_memories')
    op.drop_index('ix_user_memories_importance', table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_category'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_scenarios_goal_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_risk_assessments_user_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_user_goal', table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_scenario_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_goal_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_relationships_subject_id'), table_name='relationships')
    op.drop_index('ix_relationships_subject', table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_object_id'), table_name='relationships')
    op.drop_index('ix_relationships_object', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_pathways_scenario_id'), table_name='pathways')
    op.drop_index(op.f('ix_pathways_goal_id'), table_name='pathways')
    op.drop_index('ix_pathways_goal', table_name='pathways')
    op.drop_table('pathways')
    op.drop_index('ix_notifications_user_status', table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_risk_factor_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_event_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_metrics_name_region', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_source_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('ix_events_subject_action', table_name='events')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_assertions_source_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_scenario_id'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_index(op.f('ix_user_profiles_external_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_risk_propagation_logs_goal_id'), table_name='risk_propagation_logs')
    op.drop_index(op.f('ix_risk_propagation_logs_event_id'), table_name='risk_propagation_logs')
    op.drop_table('risk_propagation_logs')
    op.drop_index(op.f('ix_risk_factors_region'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_information_sources_user_upload_id'), table_name='information_sources')
    op.drop_table('information_sources')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_event_fingerprints_primary_event_id'), table_name='event_fingerprints')
    op.drop_index(op.f('ix_event_fingerprints_fingerprint'), table_name='event_fingerprints')
    op.drop_table('event_fingerprints')
    # ### end Alembic commands ###
