"""Conversation context compression via the configured chat model.

When a conversation grows too long for the model's context window, we
summarise the older turns into a compact system note using the chat model
itself. This preserves semantic continuity (the model still "remembers"
what was discussed) while drastically reducing token count.

Two integration points:

1. **Proactive** (``maybe_compress_history``): called before dispatching
   to the agent. Estimates token count; if it exceeds the compression
   threshold, compresses older messages.

2. **Reactive** (``compress_history_on_error``): called when the LLM API
   returns a ``context_length_exceeded`` error. Compresses and retries.

Compression strategy:
  - Keep the first user message (original ask) verbatim.
  - Keep the most recent ``keep_recent`` messages verbatim.
  - Replace everything in between with a single system message containing
    the LLM-generated summary.
  - The summary is generated by sending the to-be-compressed messages to
    the chat model with a "summarise this conversation" prompt.
"""

from __future__ import annotations

import json
from typing import Any

from app.core.exceptions import LLMNotConfiguredError
from app.core.logging import get_logger
from app.llm.client import get_chat_async_client

log = get_logger(__name__)

# Default token budget assumptions when the model's actual context window
# is unknown (we don't store context_window in the Model schema yet).
# 128k is a safe default for modern models (GPT-4o, Claude 3.5, etc.).
_DEFAULT_CONTEXT_WINDOW = 128_000

# Compress when estimated tokens exceed this fraction of the context window.
# 0.7 leaves ~30% headroom for the system prompt, tools, and the model's
# response.
_COMPRESSION_THRESHOLD_RATIO = 0.7

# How many recent messages to keep verbatim (never compress these).
# Covers the last ~2-3 turns so the model has immediate context.
_KEEP_RECENT_MESSAGES = 6

# Maximum tokens for the summary response. Short enough to be cheap,
# long enough to capture key decisions and context.
_SUMMARY_MAX_TOKENS = 800

# Minimum messages before compression kicks in — no point compressing a
# 3-message conversation.
_MIN_MESSAGES_TO_COMPRESS = 10


def estimate_tokens(text: str) -> int:
    """Rough per-message token estimate.

    Uses ``len(text) * 0.5`` as a blended estimate between English
    (~``len/3`` tokens/char) and Chinese (~``len/1.5``). Conservative on
    purpose — over-estimating slightly triggers compression a bit earlier,
    which is safer than under-estimating and blowing the context window.
    """
    if not text:
        return 0
    return int(len(text) * 0.5)


def estimate_history_tokens(history: list[dict[str, Any]]) -> int:
    """Estimate total tokens across all messages (content + tool_calls)."""
    total = 0
    for m in history:
        content = m.get("content") or ""
        if isinstance(content, str):
            total += estimate_tokens(content)
        elif isinstance(content, list):
            # Multi-part content (e.g. with images)
            for part in content:
                if isinstance(part, dict) and "text" in part:
                    total += estimate_tokens(part["text"])
        for tc in m.get("tool_calls") or []:
            try:
                total += estimate_tokens(json.dumps(tc, ensure_ascii=False))
            except (TypeError, ValueError):
                pass
        # Tool results can be large
        if m.get("role") == "tool":
            result = m.get("content") or ""
            if isinstance(result, str):
                total += estimate_tokens(result)
    return total


def should_compress(
    history: list[dict[str, Any]],
    *,
    context_window: int = _DEFAULT_CONTEXT_WINDOW,
) -> bool:
    """Return True if the history is large enough to warrant compression."""
    if len(history) < _MIN_MESSAGES_TO_COMPRESS:
        return False
    threshold = int(context_window * _COMPRESSION_THRESHOLD_RATIO)
    return estimate_history_tokens(history) > threshold


def _split_for_compression(
    history: list[dict[str, Any]],
    *,
    keep_recent: int = _KEEP_RECENT_MESSAGES,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    """Split history into (head, to_compress, tail).

    - ``head``: the first user message (original ask), kept verbatim.
    - ``to_compress``: middle messages to be summarised.
    - ``tail``: the most recent ``keep_recent`` messages, kept verbatim.
    """
    if len(history) <= keep_recent + 1:
        return history, [], []

    # Find the first user message
    first_user_idx = next(
        (i for i, m in enumerate(history) if m.get("role") == "user"),
        None,
    )
    if first_user_idx is None:
        first_user_idx = 0

    head = history[: first_user_idx + 1]
    tail = history[-keep_recent:]
    to_compress = history[first_user_idx + 1 : -keep_recent]

    return head, to_compress, tail


_SUMMARY_SYSTEM_PROMPT = """You are a conversation summarizer. Your task is to create a concise but information-dense summary of the conversation segment provided.

Focus on preserving:
- Key facts, decisions, and user preferences mentioned
- Important tool results and what was learned from them
- Any goals, plans, or action items discussed
- The current state of any ongoing task

Write the summary as a coherent paragraph (not bullet points). Keep it under 400 words. Write in the same language the user used in the conversation."""

_SUMMARY_USER_TEMPLATE = """Please summarize the following conversation segment. This summary will replace these messages in the conversation history to save context space.

Conversation to summarize:

{conversation_text}

Summary:"""


def _format_messages_for_summary(messages: list[dict[str, Any]]) -> str:
    """Format messages into a readable transcript for the summarizer."""
    lines: list[str] = []
    for m in messages:
        role = m.get("role", "unknown")
        content = m.get("content") or ""
        if isinstance(content, list):
            # Extract text from multi-part content
            content = " ".join(
                p.get("text", "") for p in content if isinstance(p, dict)
            )
        if role == "tool":
            # Truncate very long tool results
            if len(content) > 500:
                content = content[:500] + "... [truncated]"
            lines.append(f"[Tool Result] {content}")
        elif m.get("tool_calls"):
            for tc in m["tool_calls"]:
                name = tc.get("function", {}).get("name", tc.get("name", "unknown"))
                args = tc.get("function", {}).get("arguments", tc.get("args", ""))
                if isinstance(args, dict):
                    args = json.dumps(args, ensure_ascii=False)
                if len(args) > 200:
                    args = args[:200] + "..."
                lines.append(f"[Assistant called tool: {name}({args})]")
            if content:
                lines.append(f"[Assistant] {content}")
        else:
            lines.append(f"[{role.capitalize()}] {content}")
    return "\n\n".join(lines)


async def _generate_summary(
    messages_to_compress: list[dict[str, Any]],
) -> str:
    """Call the chat model to generate a summary of the given messages."""
    if not messages_to_compress:
        return ""

    transcript = _format_messages_for_summary(messages_to_compress)
    user_prompt = _SUMMARY_USER_TEMPLATE.format(conversation_text=transcript)

    try:
        client, model_name = get_chat_async_client()
    except LLMNotConfiguredError:
        log.warning("context_compression.no_chat_model")
        # No chat model configured — fall back to a simple truncation marker.
        return (
            "[Earlier conversation history could not be summarized "
            "because no chat model is configured. Key context may be lost.]"
        )

    try:
        response = await client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": _SUMMARY_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=_SUMMARY_MAX_TOKENS,
            temperature=0.1,  # Low temp for factual summary
        )
        summary = response.choices[0].message.content or ""
        summary = summary.strip()
        if summary:
            return f"[Conversation summary — earlier messages compressed]\n{summary}"
        return "[Earlier conversation history was compressed but the summary was empty.]"
    except Exception as exc:  # noqa: BLE001
        log.error("context_compression.summary_failed", error=str(exc))
        # Fall back to a truncation marker rather than failing the whole request.
        return (
            f"[Earlier conversation history compression failed: {exc}. "
            "Some context may be lost.]"
        )


async def maybe_compress_history(
    history: list[dict[str, Any]],
    *,
    context_window: int = _DEFAULT_CONTEXT_WINDOW,
    keep_recent: int = _KEEP_RECENT_MESSAGES,
) -> list[dict[str, Any]]:
    """Compress history if it exceeds the compression threshold.

    Returns the (possibly compressed) history. If compression is not
    needed or fails, returns the original history unchanged (or with
    simple truncation as a fallback).
    """
    if not should_compress(history, context_window=context_window):
        return history

    head, to_compress, tail = _split_for_compression(
        history, keep_recent=keep_recent
    )
    if not to_compress:
        return history

    log.info(
        "context_compression.compressing",
        total_messages=len(history),
        to_compress=len(to_compress),
        estimated_tokens=estimate_history_tokens(history),
    )

    summary = await _generate_summary(to_compress)
    if not summary:
        return history

    compressed = [
        *head,
        {"role": "system", "content": summary},
        *tail,
    ]

    new_tokens = estimate_history_tokens(compressed)
    old_tokens = estimate_history_tokens(history)
    log.info(
        "context_compression.done",
        old_tokens=old_tokens,
        new_tokens=new_tokens,
        reduction=old_tokens - new_tokens,
        reduction_pct=round((1 - new_tokens / max(old_tokens, 1)) * 100, 1),
    )

    return compressed


def is_context_length_error(exc: BaseException) -> bool:
    """Check if an exception is a context-length-exceeded error.

    Different providers phrase this differently, so we check several
    common patterns in the error message.
    """
    msg = str(exc).lower()
    patterns = [
        "context length",
        "context_length_exceeded",
        "maximum context length",
        "context window",
        "token limit exceeded",
        "too many tokens",
        "request too large",
        "max_tokens",
        "contextoverflow",
        "this model's maximum context length",
    ]
    return any(p in msg for p in patterns)


async def compress_history_on_error(
    history: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Force-compress history after a context_length_exceeded error.

    More aggressive than ``maybe_compress_history`` — always compresses
    (even if under the normal threshold) because we know for certain the
    context is too large.
    """
    head, to_compress, tail = _split_for_compression(
        history, keep_recent=max(_KEEP_RECENT_MESSAGES, 4)
    )
    if not to_compress:
        # Already minimal — can't compress further. As a last resort,
        # truncate the oldest messages keeping only the tail.
        return tail[-_KEEP_RECENT_MESSAGES:]

    log.warning(
        "context_compression.forced_after_error",
        total_messages=len(history),
        to_compress=len(to_compress),
    )

    summary = await _generate_summary(to_compress)
    if not summary:
        return tail[-_KEEP_RECENT_MESSAGES:]

    return [*head, {"role": "system", "content": summary}, *tail]
